config/flake8.ini
src/griffe/docstrings/rst.py
tests/test_rst.py

@plannigan, since you originally added the parser in pytkdocs, maybe you'd like to review this refactored version. Also let me know what you think is the most appropriate way to give you credits :slightly_smiling_face:  It can be as a co-author of this PR / these commits, as a comment in the module, in the module docstring, or in the repository credits, or all of these! I'll anyway add every contributor of pytkdocs to the repository credits.
A quick explanation of the changes: there's no base parser anymore, so I exploded the class into several functions. They pass the `parsed_values` around to modify it by side-effect (not sure this is the right approach now that we're not using a class). The lines can be obtained from the docstring object, which has access to the whole object tree …

feat: Add an RST-style docstring parser

---

docs/docstrings.md
src/griffe/docstrings/google.py
src/griffe/docstrings/numpy.py
tests/test_docstrings/test_google.py
tests/test_docstrings/test_numpy.py

Related to: https://github.com/mkdocstrings/mkdocstrings/issues/386
Porting the work done on the legacy handler (PR: https://github.com/mkdocstrings/pytkdocs/pull/134) over to griffe.
* ❗️feat: I added in `example` as a section_kind, in addition to `examples` for both Google and Numpy. This is aligned with `pytkdocs` and also accepted by [Sphinx Napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections). Though I understand, the official Google/Numpy docs don't seem to be explicit about whether `example` is a valid title. Let me know if there was a conscious decision made to not include "example" in Griffe before --- I'll remove it from this PR.
* ❗️fix: I renamed the `keyword_parameters` in the `section_kind` dict; I presume this was a typo since I …

feat: Add trim_doctest_flag to google and numpy parsers

---

src/griffe/docstrings/numpy.py
tests/test_docstrings/test_numpy.py

This is an attempt at fixing the current behaviour where numpydoc `Examples` sections would erroneously include the content of any following named sections until they reach an unnamed section or the end of the docstring.

Allow named sections after numpy examples

---

src/griffe/agents/nodes.py
src/griffe/collections.py
tests/test_nodes.py

Should solve #59 and [this issue](https://github.com/mkdocstrings/python/issues/8) from `mkdocstrings-python`

fix: retrieve default value for non-string parameters

---

tests/test_cli.py

Changed the output path of CLI test on Windows to a similar path. 
This should fix the Windows build error as I patched it similarly here on the `conda-forge` Windows test 👍 : https://github.com/conda-forge/griffe-feedstock/blob/befe014bfac10bb45a46ad7e19d598c34e53db99/recipe/patches/0001-windows-cli-test-patch.patch
> Reference: 
> https://stackoverflow.com/questions/313111/is-there-a-dev-null-on-windows
> https://stackoverflow.com/questions/446209/possible-values-from-sys-platform

tests: Fix CLI Test on Windows

---

src/griffe/dataclasses.py
src/griffe/docstrings/google.py
tests/test_docstrings/test_google.py

Reference: https://github.com/mkdocstrings/mkdocstrings/issues/408

feat: warn if docstring has extra parameters

---

src/griffe/cli.py
src/griffe/dataclasses.py
src/griffe/mixins.py
tests/test_encoders.py

👋
I wonder if you'd consider this PR that adds some serialization/deserialization convenience methods to `dataclasses.Object`.  When using programmatically, it makes it easier to construct/deconstruct from serialized.
I made it a mixin that could be added to other objects (since _many_ of the objects here could theoretically be supported), but I stopped short of adding it to anything besides Object.  (but `ModulesCollection`, for example, would be another prime candidate).
One of the nice things this does is support type hinting:
```python
from griffe.dataclasses import Module
mod = Module.from_json('{...}')
reveal_type(mod)  # type of "mod" is "Module"
```

feat: add to/from_json convenience methods to Object

---

duties.py
src/griffe/finder.py
src/griffe/loader.py

Always use `encoding="utf8"` when reading text files.

---

src/griffe/dataclasses.py
src/griffe/mixins.py

fix: Guard against more alias resolution errors

---

src/griffe/agents/nodes.py
tests/test_nodes.py

Previously a value like `o[x, y(z)]` would be unparsed as `o[x, y(z]` (missing right parenthesis). Reported on Gitter.

fix: Don't strip too many parentheses on the right of a call node

---

src/griffe/docstrings/numpy.py
tests/test_docstrings/test_numpy.py

I've fixed support for NumPy annotations, that aren't conformant with PEP 484, for additional docstring sections:
* Attributes
* Returns
* Receives
* Yields
Follow-up of 75eeeda2f1181ae680b3d47df3814bad200220d3. Fixes https://github.com/mkdocstrings/griffe/issues/93#issuecomment-1291784022.

fix: Log debug instead of errors when failing to parse NumPy annotations for additional sections

---

src/griffe/agents/visitor.py

Support `overload` from `typing_extensions` as it was introduced in [4.2.0](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md#release-420-april-17-2022), allowing runtime inspection of overloads.

feat: support typing_extensions.overload

---

README.md
config/flake8.ini
pyproject.toml
src/griffe/__init__.py
src/griffe/agents/visitor.py
src/griffe/cli.py
src/griffe/dataclasses.py
src/griffe/diff.py
src/griffe/expressions.py
src/griffe/git.py
tests/test_cli.py
tests/test_diff.py
tests/test_encoders.py
tests/test_functions.py
tests/test_git.py

Co-authored-by: Talley Lambert <talley.lambert@gmail.com>
---
@tlambert03, following discussion in #75, I've taken your code in griffediff, updated it to my taste (I hope you don't mind :sweat:) and credited you of course. This PR is still a draft anyway, just experimenting a bit.
What I envision is:
- utility to yield more than breakages: yield everything that changed or was added/removed (for auto-documentation purposes) and attach these data to objects
- also attach detected breakages to objects
- utility to yield forward-compatibility hints: "set these parameters as keyword-only" here and there, etc., and attach these data to objects. These hints could be displayed in docs auto-generated through mkdocstrings when serving only, to inform the developer :thinking:
- of course: add CLI …

feat: Add function to find API breaking changes

---

README.md
src/griffe/collections.py
src/griffe/dataclasses.py
tests/test_dataclasses.py

Fix deepcopy issue

---

src/griffe/finder.py
tests/test_finder.py

Python packages may have multiple root modules where each is installed to its own folder under `site-packages`.
When using new setuptools editable install in such cases griffe, when used by mkdocstrings fails to find the correct paths.
The root cause it that griffe assumed a variable named `MAPPING` in the `.py` file created by the editable install, and assumed that this variable is a dict with single entry.
When a package has multiple roots - then this dictionary contain multiple entries.
This PR aims to handle such cases.
I have no knowledge about `editables` so I could not fix that case.
The unit test added simulates the case, and this has been tested against a real complex package with multiple roots using setuptools 65 editable install.

fix: support editable install with multiple roots

---

README.md
docs/checking.md
docs/dumping.md
docs/loading.md
src/griffe/docstrings/google.py

Just a couple of typo fixes to the docs.
And I realized the output of `griffe dump` is an object, not an array anymore, so updated the docs to reflect that

docs: minor typo fixes

---

src/griffe/agents/visitor.py
tests/test_visitor.py

This will fix #128.
Thanks for the guidance, @pawamoy.
I tried doing what was needed (follow commit message format conventions, add the test in the correct place, etc) but I might have missed something.
If so, please let me know.

feat: Forward class attribute docstrings to instances.

---

src/griffe/docstrings/google.py
tests/test_docstrings/test_google.py

According to the documentation it's possible to start a description with a newline.
However, this did not work properly for Raises and Warns sections, because of a stray space in the regex to split the annotation and its description.

fix: Allow Raises and Warns sections to start with a newline

---

src/griffe/agents/visitor.py
src/griffe/expressions.py
tests/test_visitor.py

According to [PEP 526](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations) annotated attributes in a class body are instance variables by default, unless explicitly overridden by using [`typing.ClassVar`](https://docs.python.org/3/library/typing.html#typing.ClassVar).
This PR makes 2 changes:
1. Honor `typing.ClassVar` in class variable annotations.
2. Merge the annotations in the class body and in `__init__()`.

Respect ClassVar variable annotation

---

src/griffe/docstrings/google.py

The `Warns` sections of google docstrings were incorrectly marked as `Attributes`. I saw this while trying to build a site using `mkdocstrings-python`.

fix: google docstrings warns section

---

docs/docstrings.md
src/griffe/docstrings/numpy.py
tests/test_docstrings/test_numpy.py

This PR addresses #167. I'm happy to tweak / look into supporting different cases. (I've xfailed the test of what would be a breaking change, and added a test of the new supported behavior.)

Fix numpy block linebreaks

---

src/griffe/finder.py
tests/test_finder.py

Addresses #172, by supporting semi-colons in pth files. Thanks for your quick response in the issue! Happy to make any changes :)

fix: parse pth files with semi-colons as breaks

---

README.md
docs/loading.md
src/griffe/agents/inspector.py
src/griffe/agents/nodes.py
src/griffe/agents/visitor.py
src/griffe/c3linear.py
src/griffe/collections.py
src/griffe/dataclasses.py
src/griffe/encoders.py
src/griffe/expressions.py
src/griffe/extensions/hybrid.py
src/griffe/loader.py
src/griffe/merger.py
src/griffe/mixins.py
src/griffe/tests.py
tests/test_inheritance.py
tests/test_stdlib.py

Closes #138
Closes #153 
Unblocks work on #96, https://github.com/mkdocstrings/python/issues/40, https://github.com/mkdocstrings/python/issues/13
Related to https://github.com/mkdocstrings/mkdocstrings/issues/459, https://github.com/mkdocstrings/mkdocstrings/issues/157, https://github.com/mkdocstrings/mkdocstrings/discussions/536
Tagging people who are probably interested: @samsja, @tazend, @cpcloud, @famura, @machow, @gab832, @analog-cbarber, @jayqi, @chrieke, @tristanlatr
Feel free to tag others. Also, subscribe to this PR to get future notifications: I'll explain the changes in this PR later so that we can discuss them. Or unsubscribe to stop getting notifications :slightly_smiling_face: 
---
Explanation:
- the inspector only picks up non-inherited members
- the visitor does not change …

feat: Support inheritance

---

src/griffe/c3linear.py
src/griffe/cli.py
src/griffe/mixins.py
tests/test_inspector.py

Hi,
This PR adds `--version` and `-V` command line flags to `griffe`.
Should I also add the version information to the common options?
This PR also closes #186.
I also added two commits fixing a typo in a docstring and improving the return description.

feat: Add `--version` and `-V` cli flag.

---

docs/docstrings.md
docs/schema-docstrings-options.json
src/griffe/docstrings/google.py
tests/test_docstrings/test_google.py

BTW, `make format` is failing on my machine:
```console
❯ make format
bash: line 1: duty: command not found
make: *** [format] Error 127
```

feat: Google docstrings Returns section can be parsed with or without multiple items

---

src/griffe/dataclasses.py
src/griffe/mixins.py

In sync with https://github.com/mkdocstrings/python/pull/99

fix: Preserve alias members path

---

docs/docstrings.md
src/griffe/docstrings/google.py
tests/test_docstrings/test_google.py

Comment https://github.com/mkdocstrings/griffe/issues/137#issuecomment-1673650474

feat: Read return type of properties in their summary

---

src/griffe/dataclasses.py

While having a look at the source code, I realized that `filepath` was being incorrectly dumped as a string when being a list of paths, rather than as a list of strings.
```
"filepath": "[PosixPath('mod'), PosixPath('/home/davfsa/coding/test_mod')]"
```
vs
```
"filepath": [
"mod",
"/home/davfsa/coding/test_mod"
]
```
---
I have not added any tests, due to the lack of them in the module (at the time of writing). If it were needed, I could write it up :)

Fix dumping "filepath" to a dict when it is a list

---

docs/extensions.md

`super().__init__()` does not take a self parameter

fix super().__init__() calls in docs/extensions.md

---

src/griffe/cli.py
src/griffe/finder.py
src/griffe/git.py
src/griffe/loader.py
src/griffe/merger.py
tests/test_finder.py
tests/test_loader.py

Small change to look for X-stubs first when looking for the X module. This better respects PEP 561.
Incidental fix to properly recognize a stubs only package as a package (and not a namespace package).
Please let me know if this is the correct approach (it works for my use case). I can also try to add tests if this is something that is mergeable. I tried to keep my changes to a minimal (being totally unfamiliar with the code).

feat: Allow the use of *-stubs packages

---

src/griffe/diff.py
tests/test_diff.py

This PR Address the #218 issue. 
Describe the bug
For example, going from:
```
class A:
b: int | None = None
```
to
```
class A:
b: int
```
will report
`Attribute value was changed: None -> None`
Now modified to 
`Attribute value was changed: None -> unset`

fix: reporting the attribute who lost their value

---

docs/docstrings.md
src/griffe/docstrings/google.py
src/griffe/docstrings/numpy.py
tests/test_docstrings/test_numpy.py
tests/test_inspector.py

Related to PR #219: https://github.com/mkdocstrings/griffe/pull/219
@machow

fix: Consider space-only lines to be empty

---

src/griffe/docstrings/dataclasses.py
src/griffe/docstrings/numpy.py
tests/test_docstrings/test_numpy.py

This PR fixes a bug in the NumpyDoc parser where the Warnings section would render as a note admonition. They now render as warning admonitions.
I felt bad opening an issue about this after accusing the NumpyDoc parser of being buggy yesterday, so thought I'd at least contribute this one myself 😄

Add special case for NumpyDoc warnings section so they render as warning admonitions

---

src/griffe/agents/inspector.py
src/griffe/agents/visitor.py
src/griffe/dataclasses.py
src/griffe/expressions.py
src/griffe/extensions/base.py
src/griffe/extensions/dataclasses.py
src/griffe/loader.py
tests/test_dataclasses.py
tests/test_docstrings/test_google.py

Closes #233, #234, #238, #239.
TODO:

feat: Better support for dataclasses

---

src/griffe/extensions/dataclasses.py
tests/test_dataclasses.py

This was fixed in 5a5c03b, but broken in 82a9d57. The tests
broke as well and did not catch the regression.

fix: Fix dataclass parameters to exclude properties

---

src/griffe/extensions/dataclasses.py
tests/test_dataclasses.py

This PR addresses the case of dataclass [init-only variables](https://docs.python.org/3/library/dataclasses.html#init-only-variables) also being treated as class members. i.e
```python
from dataclasses import dataclass, InitVar
@dataclass
class Point:
x: float
y: float
z: InitVar[float]
```
is equivalent (compatible) to
```python
class Point:
def __init__(self, x: float, y: float, z: float):
self.x = x
self.y = y
```
The class is not expected to have member `z` (`instance.z`).

fix: Don't turn items annotated as InitVar into dataclass members

---

src/griffe/extensions/dataclasses.py
tests/test_dataclasses.py

All dataclass parameters have annotations. When determining
which of the attributes of dataclass are parameters, we
explicitly check against that condition. This help us filter
out obvious non-candidates that may otherwise fall through.

fix: Attributes without annotations cannot be parameters

---

docs/reference/docstrings.md
src/_griffe/docstrings/google.py
tests/test_docstrings/test_google.py

This PR fixes https://github.com/mkdocstrings/griffe/issues/263 by applying the same logic from the `Returns` section parser to the `Yields` and `Receives` parser.  The `Yields` section parser is configured with the same two configuration variables `returns_multiple_items` and `returns_named_value`, whereas the `Receives` section parser is configured via the new `receives_multiple_items` and `receives_named_value` configuration variables. Furthermore, the parsing of multiple or single docstring block contents, of named or unnamed parameters, and the unpacking of generator and/or tuple return annotations has been refactored into separate functions.
---
<b>Contents:</b>
- 8a78e68e7702d5b874daa21aeca58943eb9cf7d6 duplicates the non-multiple return and the named value parsing support for the …

Support non-multiple and non-named values in Yields and Receives

---

src/_griffe/loader.py

Thank you for all the work on mkdocstrings! Tiny fix, I noticed that some of the messages read like
```
DEBUG   -  griffe: Iteration 1 finished, {len(resolved)} aliases resolved, still {len(unresolved)} to go
```

Fix: f-string inclusion in debug msg

---

Makefile

Add explicit comments explaining the purpose of the help target and .DEFAULT_GOAL. This improves readability and makes the Makefile's behavior more transparent.
See https://www.gnu.org/software/make/manual/html_node/Goals.html and https://stackoverflow.com/a/43719512/19489416
The most impactful effect is that now, simply calling "make" will show the help, instead of a weird error (weird for newcomers, like me this weekend). If you like this pattern, feel free to apply it to the other repos that use the same structure.
Before:
After:
<details><summary>Console output as text for easier searching:</summary>
<p>
```
vscode ➜ /workspaces/griffe (makefile-help-default) $ make
Available commands
help                  Print this help. Add task name to print help.
setup                 Setup all …
```

chore(makefile): set help target as default goal

---

src/_griffe/expressions.py

Fixed typing annotation following discussion comment: https://github.com/mkdocstrings/griffe/discussions/391#discussioncomment-13698603

fix: Allow `ExprName.parent` to be of type `griffe.Function`

---

src/_griffe/docstrings/sphinx.py
tests/test_docstrings/test_sphinx.py

This PR enhances the parsing of `:param xxxx yyyy:` tags in the sphinx style docstrings, when the type in the middle is invalid because of added spaces (not single word).
According [to these sphinx docs](https://www.sphinx-doc.org/en/master/usage/domains/python.html#info-field-lists), the types and parameters can be combined only when there are no spaces in the type: 
> It is also possible to combine parameter type and description, if the type is a single word, like this:
> ```rest
> :param int priority: The priority of the message, can be a number 1-5
> ```
When there are spaces, there are more than 3 elements in the `directive_parts` of the `parsed_directive`. Before this PR, the whole parameter would be skipped (optionally showing warnings) and just not shown in the rendered docs, and …

feat: Enhance parameter parsing to handle invalid type info and add related tests

---

src/_griffe/finder.py
src/_griffe/loader.py
tests/test_loader.py

Changed the encoding from `utf8` to `utf-8-sig` when reading files, in order to ignore a possible byte-order mark (a.k.a. BOM, code point U+FEFF) at the start of the file.
As per the Python documentation:
> In some areas, it is also convention to use a “BOM” at the start of
> UTF-8 encoded files; the name is misleading since UTF-8 is not
> byte-order dependent. The mark simply announces that the file is
> encoded in UTF-8. For reading such files, use the ‘utf-8-sig’ codec
> to automatically skip the mark if present.
https://docs.python.org/3/howto/unicode.html#reading-and-writing-unicode-data
So this change won't affect reading UTF8-encoded files without a BOM.
Fixes #386.

Always use `encoding="utf-8-sig"` when reading text files

---

src/griffe/_internal/extensions/unpack_typeddict.py
tests/test_extensions/test_unpack_typeddict.py

See https://github.com/mkdocstrings/python/issues/207.
Instead of expanding to named-args + kwargs for non-required fields, we expand to only named-args + `...` as default value for non-required fields. `extra_items` is not yet supported (nor is `closed`). Will do when someone requests support (feature in 3.15).
- https://github.com/mkdocstrings/python/issues/207
- https://github.com/mkdocstrings/griffe/issues/284

refactor: Improve handling of typed dicts
